# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3ef1609d-9031-49c5-be07-20844efe4354";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/30047ffe-3056-4a97-9f3f-17bfe319f8d4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
